/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CentralSolicitacoesRouteImport } from './routes/central-solicitacoes'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CentralSolicitacoesIndexRouteImport } from './routes/central-solicitacoes.index'
import { Route as CentralSolicitacoesAjustePtrRouteImport } from './routes/central-solicitacoes.ajuste-ptr'

const CentralSolicitacoesRoute = CentralSolicitacoesRouteImport.update({
  id: '/central-solicitacoes',
  path: '/central-solicitacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralSolicitacoesIndexRoute =
  CentralSolicitacoesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CentralSolicitacoesRoute,
  } as any)
const CentralSolicitacoesAjustePtrRoute =
  CentralSolicitacoesAjustePtrRouteImport.update({
    id: '/ajuste-ptr',
    path: '/ajuste-ptr',
    getParentRoute: () => CentralSolicitacoesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/central-solicitacoes': typeof CentralSolicitacoesRouteWithChildren
  '/central-solicitacoes/ajuste-ptr': typeof CentralSolicitacoesAjustePtrRoute
  '/central-solicitacoes/': typeof CentralSolicitacoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/central-solicitacoes/ajuste-ptr': typeof CentralSolicitacoesAjustePtrRoute
  '/central-solicitacoes': typeof CentralSolicitacoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/central-solicitacoes': typeof CentralSolicitacoesRouteWithChildren
  '/central-solicitacoes/ajuste-ptr': typeof CentralSolicitacoesAjustePtrRoute
  '/central-solicitacoes/': typeof CentralSolicitacoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajuda'
    | '/central-solicitacoes'
    | '/central-solicitacoes/ajuste-ptr'
    | '/central-solicitacoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajuda'
    | '/central-solicitacoes/ajuste-ptr'
    | '/central-solicitacoes'
  id:
    | '__root__'
    | '/'
    | '/ajuda'
    | '/central-solicitacoes'
    | '/central-solicitacoes/ajuste-ptr'
    | '/central-solicitacoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjudaRoute: typeof AjudaRoute
  CentralSolicitacoesRoute: typeof CentralSolicitacoesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/central-solicitacoes': {
      id: '/central-solicitacoes'
      path: '/central-solicitacoes'
      fullPath: '/central-solicitacoes'
      preLoaderRoute: typeof CentralSolicitacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central-solicitacoes/': {
      id: '/central-solicitacoes/'
      path: '/'
      fullPath: '/central-solicitacoes/'
      preLoaderRoute: typeof CentralSolicitacoesIndexRouteImport
      parentRoute: typeof CentralSolicitacoesRoute
    }
    '/central-solicitacoes/ajuste-ptr': {
      id: '/central-solicitacoes/ajuste-ptr'
      path: '/ajuste-ptr'
      fullPath: '/central-solicitacoes/ajuste-ptr'
      preLoaderRoute: typeof CentralSolicitacoesAjustePtrRouteImport
      parentRoute: typeof CentralSolicitacoesRoute
    }
  }
}

interface CentralSolicitacoesRouteChildren {
  CentralSolicitacoesAjustePtrRoute: typeof CentralSolicitacoesAjustePtrRoute
  CentralSolicitacoesIndexRoute: typeof CentralSolicitacoesIndexRoute
}

const CentralSolicitacoesRouteChildren: CentralSolicitacoesRouteChildren = {
  CentralSolicitacoesAjustePtrRoute: CentralSolicitacoesAjustePtrRoute,
  CentralSolicitacoesIndexRoute: CentralSolicitacoesIndexRoute,
}

const CentralSolicitacoesRouteWithChildren =
  CentralSolicitacoesRoute._addFileChildren(CentralSolicitacoesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjudaRoute: AjudaRoute,
  CentralSolicitacoesRoute: CentralSolicitacoesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
